apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: prometheus-meta
spec:
  alerting:
    alertmanagers:
      - name: alertmanager-main
        namespace: monitoring
        port: web
  podMonitorSelector: {}
  probeSelector: {}
  replicas: 1
  ruleSelector: {}
  serviceAccountName: prometheus-k8s
  serviceMonitorSelector: {}
