apiVersion: monitoring.coreos.com/v1
kind: Probe
metadata:
  name: example
spec:
  jobName: example
  prober:
    url: blackbox-prometheus-blackbox-exporter:9115
  targets:
    ingress:
      namespaceSelector:
        matchNames:
          - default
      selector:
        matchLabels:
          probe: example
    interval: 15s
    module: http_2xx
