apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: example
spec:
  endpoints:
    - interval: 30s
      port: web
  selector:
    matchLabels:
      operated-prometheus: "true"
