apiVersion: monitoring.coreos.com/v1alpha1
kind: PrometheusAgent
metadata:
  name: Prometheus-Ag
spec:
  podMonitorSelector: {}
  probeSelector: {}
  replicas: 1
  ruleSelector: {}
  serviceAccountName: prometheus-k8s
  serviceMonitorSelector: {}
